### ISSUE TITLE
Improve the design of the 'there HAS been a change' page

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/2015wards#2]

**Comment by stevenday** [comment]
The "Your ward may have changed, please see the map." text can be more confident now - if we think it's changed, it has.

**Comment by dracos** [comment]
@stevenday Afraid not, that's why I changed it to that text – e.g. http://steve.2015wards.dev.mysociety.org/postcode/BB27NT (differs by c 8000)

**Comment by TomSteinberg** [comment]
Note to designers - if you can fit a 'Share this on facebook' button to this page that would be nice, but really not worth more than about max 60 minutes work.

**Comment by TomSteinberg** [comment]
Suggested text:

On election day (7th May 2015), you'll be in _____  ward.

===== Old ward

===== New ward

If you can't see much or any pink, that's probably because the ward boundaries haven't actually changed.

Want to know more about the boundaries for this ward? Visit the Local Government Boundary Commission's website to see full details of any changes.

New! Find out about your general election candidates at YourNextMP.com'
